# Generated by Django 5.1.1 on 2024-10-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gear',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='gear',
            name='category',
            field=models.CharField(choices=[('tents', 'Tents'), ('sleeping-bags', 'Sleeping Bags'), ('entertainment', 'Entertainment')], default='camping', max_length=50),
        ),
        migrations.AddField(
            model_name='gear',
            name='image',
            field=models.ImageField(default='https://media.baamboozle.com/uploads/images/1197896/1677692362_34951_gif-url.gif', upload_to='images/'),
        ),
    ]
